STEAPP-499: added move down on 5mm when change extruders.
stereotech/klipper pull request #128
Opened 2023-05-22 15:12 UTC by SokolovJek

2023-05-29 07:08 UTC, frylock34 requested changes

2023-05-29 07:08 UTC, frylock34 commented on stereotech_config/main_extruder.cfg
> +[gcode_macro MOVE_DOWN_Z_AXIS]
Если этот код переиспользуемый, то почему не добавить его в `print_macros.cfg`

2023-05-29 07:08 UTC, frylock34 commented on stereotech_config/main_extruder.cfg
>      {% if "x" in printer.toolhead.homed_axes and "y" in printer.toolhead.homed_axes and printer.toolhead.extruder != 'extruder' %}
Тут нужна проверка запаркована ли ось Z

2023-06-13 09:22 UTC, SokolovJek commented on stereotech_config/main_extruder.cfg
>      {% if "x" in printer.toolhead.homed_axes and "y" in printer.toolhead.homed_axes and printer.toolhead.extruder != 'extruder' %}
проверка была но глубже в макросе MOVE_DOWN_Z_AXIS

2023-06-22 12:04 UTC, merged